### ISSUE TITLE
hey i recommend also thumbnail of videos

### ISSUE THREAD

**Issue by Felsaspalt** [Sceneworker/YoutubePlaylistVideoTitle#1]
this is not issue but must be perfect if this will also be put in

**Comment by DanielOberlechner** [comment]
Hi @Felsaspalt 
I have some spare time I could implement that feature.
In my case it doesn't make sense just I simply need a backup list of all songs in my youtube playlist. But if I've time I could implement it for you!

Kind regards,
Daniel :)

**Comment by DanielOberlechner** [comment]
@Felsaspalt 
Hi,
I had some free time to build a new function which does download all thumbnails from the playlist and save them into the folder of the project named thumbnails. If you would like to check it out just do so.

Hope I've helped you a little bit with that function! 

Greets,
Daniel :)

**Comment by Felsaspalt** [comment]
Thank you very much, I can feedback later
